server {
    listen 80;
    server_name lsp-v3.local;

    root /var/www/html;
    index index.php index.html;

    client_max_body_size 200M;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass native-app:9000;  # harus sama nama container PHP
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
    }

    location ~ /\.ht {
        deny all;
    }
}
